### ISSUE TITLE
Difference between dist_chamfer.py and chamfer_python.py

### ISSUE THREAD

**Issue by Taeuk-Jang** [ThibaultGROUEIX/chamfer_pytorch#1]
what are the difference between those?

**Comment by ThibaultGROUEIX** [comment]
Dear Taeuk-Jang,

`dist_chamfer` : Cuda code, has to be compiled, fast -> good for performance
`chamfer_python` : python code, no compilation needed, slow. -> good for quick testing

Cheers,
Thibault
