### ISSUE TITLE
What's the difference between dist_chamfer_idx.py and dist_chamfer.py

### ISSUE THREAD

**Issue by tornadomeet** [ThibaultGROUEIX/chamfer_pytorch#3]
hello, @ThibaultGROUEIX  

It's seems that 
https://github.com/ThibaultGROUEIX/chamfer_pytorch/blob/master/dist_chamfer_idx.py  and https://github.com/ThibaultGROUEIX/chamfer_pytorch/blob/master/dist_chamfer.py
is the same, is it right?  thanks.

**Comment by ThibaultGROUEIX** [comment]
Hi @tornadomeet ,
`dist_chamfer_id`  also returns the index of the closest points. 
https://github.com/ThibaultGROUEIX/chamfer_pytorch/blob/master/dist_chamfer_idx.py#L28

It can be useful depending on what you're trying to do.
Best regards,
Thibault

**Comment by tornadomeet** [comment]
@ThibaultGROUEIX  got it, thanks!
